apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-k8s-app
  template:
    metadata:
      labels:
        app: flask-k8s-app
    spec:
      containers:
      - name: flask-container
        image: yourdockerhub/flask-k8s-demo:latest
        ports:
        - containerPort: 5000
