apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
spec:
  type: NodePort
  selector:
    app: flask-k8s-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
